version: '3.8'

services:
  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '50051:50051'
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - MONGO_URI=mongodb://mongodb:27017
  #   networks:
  #     - auth-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - auth-network
    volumes:
      - mongo-data:/data/db

networks:
  auth-network:
    driver: bridge

volumes:
  mongo-data:
